version: '3.8'

services:
  voc-classifier:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount external drive for model storage
      - ./models_cache:/app/models_cache
      - ./logs:/app/logs
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - TRANSFORMERS_CACHE=/app/models_cache
      - HF_HOME=/app/models_cache
      - CUDA_VISIBLE_DEVICES=0  # Enable GPU if available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - voc-classifier
    restart: unless-stopped
    profiles: ["production"]