name: voc-classifier-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.13
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cpuonly  # CPU-only version
  - pillow>=9.5.0
  - pip
  - pip:
    - transformers>=4.45.0
    - accelerate>=0.25.0